<?php
$templates = [
    'render' => __DIR__ . '/templates/template.php',
    'content' => __DIR__ . '/templates/content.php',
];

$titleFields = [
    'title' => ['label' => 'Facet Title', 'type' => 'text'],
    'title_style' => [
        'label' => 'Style',
        'description' => 'Title styles differ in font-size but may also come with a predefined color, size and font.',
        'type' => 'select',
        'options' => [
            'None' => '',
            'Text Meta' => 'text-meta',
            'Text Lead' => 'text-lead',
            'Text Small' => 'text-small',
            'Text Large' => 'text-large',
            'Heading 3X-Large' => 'heading-3xlarge',
            'Heading 2X-Large' => 'heading-2xlarge',
            'Heading X-Large' => 'heading-xlarge',
            'Heading Large' => 'heading-large',
            'Heading Medium' => 'heading-medium',
            'Heading Small' => 'heading-small',
            'Heading H1' => 'h1',
            'Heading H2' => 'h2',
            'Heading H3' => 'h3',
            'Heading H4' => 'h4',
            'Heading H5' => 'h5',
            'Heading H6' => 'h6',
        ],
        'enable' => 'title',
    ],
    'title_decoration' => [
        'label' => 'Decoration',
        'description' => 'Decorate the title with a divider, bullet or a line that is vertically centered to the heading.',
        'type' => 'select',
        'options' => [
            'None' => '',
            'Divider' => 'divider',
            'Bullet' => 'bullet',
            'Line' => 'line',
        ],
        'enable' => 'title',
    ],
    'title_font_family' => [
        'label' => 'Font Family',
        'description' => 'Select an alternative font family. Mind that not all styles have different font families.',
        'type' => 'select',
        'options' => [
            'None' => '',
            'Default' => 'default',
            'Primary' => 'primary',
            'Secondary' => 'secondary',
            'Tertiary' => 'tertiary',
        ],
        'enable' => 'title',
    ],
    'title_color' => [
        'label' => 'Color',
        'description' => 'Select the text color. If the Background option is selected, styles that don\'t apply a background image use the primary color instead.',
        'type' => 'select',
        'options' => [
            'None' => '',
            'Muted' => 'muted',
            'Emphasis' => 'emphasis',
            'Primary' => 'primary',
            'Secondary' => 'secondary',
            'Success' => 'success',
            'Warning' => 'warning',
            'Danger' => 'danger',
            'Background' => 'background',
        ],
        'enable' => 'title',
    ],
    'title_element' => [
        'label' => 'HTML Element',
        'description' => 'Set the level for the section heading or give it no semantic meaning.',
        'type' => 'select',
        'options' => [
            'h1' => 'h1',
            'h2' => 'h2',
            'h3' => 'h3',
            'h4' => 'h4',
            'h5' => 'h5',
            'h6' => 'h6',
            'div' => 'div',
        ],
        'enable' => 'title',
    ],
];
$generalFields = ['position', 'position_left', 'position_right', 'position_top', 'position_bottom', 'position_z_index', 'margin_top', 'margin_bottom', 'maxwidth', 'maxwidth_breakpoint', 'block_align', 'block_align_breakpoint', 'block_align_fallback', 'text_align', 'text_align_breakpoint', 'text_align_fallback', 'animation', '_parallax_button', 'visibility'];
$cssHints = ['.el-element', '.el-item', '.el-title', '.el-meta', '.el-content', '.el-image', '.el-link'];

return [
    'name' => 'instantsearch_facet',
    'title' => 'Facet Filter',
    'group' => 'Instant Search',
    'icon' => '${url:svg/icon.svg}',
    'iconSmall' => '${url:svg/iconSmall.svg}',
    'element' => true,
    'width' => 500,
    'templates' => $templates,
    'defaults' => [
        'margin_top' => 'default',
        'margin_bottom' => 'default',
        'content_more' => 'Show More',
        'content_less' => 'Show Less',
        'icon' => 'close',
        'icon_less' => 'close',
        'button_style' => 'default',
        'icon_align' => 'right',
        'show_more' => true,
        'show_more_limit' => '50',
        'title_element' => 'h6',
        'limit' => 10,
        'enable_all_button' => true,
        'all_button_text' => 'All',
        'facet_type' => 'checkbox',
        'sort_by' => 'isRefined:desc',
        'sort_by_fallback' => 'name:asc',
    ],
    'fields' => array_merge($titleFields, [
        'facet' => ['type' => 'text', 'label' => 'Facet'],
        'facet_type' => ['label' => 'Facet Type', 'type' => 'select', 'options' => ['Checkbox' => 'checkbox', 'Radio' => 'radio']],
        'item_count' => ['label' => 'Show item count', 'type' => 'checkbox', 'text' => 'Enable'],
        'limit' => ['label' => 'Limit Facets', 'type' => 'number'],
        'correct_order' => ['label' => 'Facet Order', 'type' => 'yooessentials-settings-panel', 'panel' => 'instantsearch-facets-order'],
        'show_more' => ['label' => 'Enable', 'type' => 'checkbox', 'text' => 'Enable Show More Button'],
        'show_more_limit' => ['type' => 'text', 'label' => 'Limit', 'enable' => 'show_more'],
        'content_more' => ['label' => '\'Show More\' Label', 'source' => true, 'enable' => 'show_more'],
        'content_less' => ['label' => '\'Show Less\' Label', 'source' => true, 'enable' => 'show_more'],
        'button_style' => ['label' => 'Style', 'description' => 'Set the button style.', 'type' => 'select', 'options' => ['Default' => 'default', 'Primary' => 'primary', 'Secondary' => 'secondary', 'Danger' => 'danger', 'Text' => 'text', 'Link' => '', 'Link Muted' => 'link-muted', 'Link Text' => 'link-text'], 'enable' => 'show_more'],
        'button_size' => ['label' => 'Size', 'type' => 'select', 'options' => ['Small' => 'small', 'Default' => '', 'Large' => 'large'], 'enable' => 'show_more'],
        'fullwidth' => ['type' => 'checkbox', 'text' => 'Full width button', 'enable' => 'show_more'],
        'icon' => ['label' => 'Icon Show More', 'description' => 'Pick an optional icon.', 'type' => 'icon', 'source' => true, 'enable' => 'show_more'],
        'icon_less' => ['label' => 'Icon Show Less', 'description' => 'Pick an optional icon.', 'type' => 'icon', 'source' => true, 'enable' => 'show_more'],
        'icon_align' => ['label' => 'Alignment', 'description' => 'Choose the icon position.', 'type' => 'select', 'options' => ['Left' => 'left', 'Right' => 'right'], 'enable' => 'show_more'],
        'enable_all_button' => ['label' => 'Enable All Button', 'type' => 'checkbox', 'text' => 'Enable'],
        'all_button_text' => ['label' => 'All Button Text', 'enable' => 'enable_all_button'],
        'sort_by' => ['label' => 'Primary', 'type' => 'select', 'options' => ['Hits Count (Desc)' => 'count:desc', 'Hits Count (Asc)' => 'count:asc', 'Name (Desc)' => 'name:desc', 'Name (Asc)' => 'name:asc', 'Is Refined (Desc)' => 'isRefined:desc', 'Is Refined (Asc)' => 'isRefined:asc']],
        'sort_by_fallback' => ['label' => 'Fallback', 'type' => 'select', 'options' => ['None' => null, 'Hits Count (Desc)' => 'count:desc', 'Hits Count (Asc)' => 'count:asc', 'Name (Desc)' => 'name:desc', 'Name (Asc)' => 'name:asc', 'Is Refined (Desc)' => 'isRefined:desc', 'Is Refined (Asc)' => 'isRefined:asc']],
        'position' => '${builder.position}', 'position_left' => '${builder.position_left}', 'position_right' => '${builder.position_right}', 'position_top' => '${builder.position_top}', 'position_bottom' => '${builder.position_bottom}', 'position_z_index' => '${builder.position_z_index}', 'margin_top' => '${builder.margin_top}', 'margin_bottom' => '${builder.margin_bottom}', 'maxwidth' => '${builder.maxwidth}', 'maxwidth_breakpoint' => '${builder.maxwidth_breakpoint}', 'block_align' => '${builder.block_align}', 'block_align_breakpoint' => '${builder.block_align_breakpoint}', 'block_align_fallback' => '${builder.block_align_fallback}', 'text_align' => '${builder.text_align_justify}', 'text_align_breakpoint' => '${builder.text_align_breakpoint}', 'text_align_fallback' => '${builder.text_align_justify_fallback}', 'animation' => '${builder.animation}', '_parallax_button' => '${builder._parallax_button}', 'visibility' => '${builder.visibility}', 'name' => '${builder.name}', 'status' => '${builder.status}', 'id' => '${builder.id}', 'class' => '${builder.cls}', 'attributes' => '${builder.attrs}', 'css' => ['label' => 'CSS', 'description' => 'Enter your own custom CSS. The following selectors will be prefixed automatically for this element: ' . implode(', ', array_map(fn($hint) => "<code>{$hint}</code>", $cssHints)), 'type' => 'editor', 'editor' => 'code', 'mode' => 'css', 'attrs' => ['debounce' => 500, 'hints' => $cssHints], 'source' => true],
    ]),
    'fieldset' => ['default' => ['type' => 'tabs', 'fields' => [
        [
            'title' => 'Content',
            'fields' => [
                [
                    'label' => 'Facet',
                    'type' => 'group',
                    'divider' => true,
                    'fields' => ['facet', 'facet_type', 'item_count', 'limit', 'correct_order'],
                ],
                [
                    'label' => 'Title',
                    'type' => 'group',
                    'divider' => true,
                    'fields' => ['title'],
                ],
                [
                    'label' => 'All Button',
                    'type' => 'group',
                    'divider' => false,
                    'fields' => ['enable_all_button', 'all_button_text'],
                ],
            ],
        ],
        [
            'title' => 'Settings',
            'fields' => [
                [
                    'label' => 'Show More Button',
                    'type' => 'group',
                    'divider' => true,
                    'fields' => ['show_more', 'show_more_limit', 'content_more', 'content_less', 'icon', 'icon_less', 'icon_align', 'button_style', 'button_size', 'fullwidth'],
                ],
                [
                    'label' => 'Sorting',
                    'type' => 'group',
                    'divider' => true,
                    'fields' => ['sort_by', 'sort_by_fallback'],
                ],
                [
                    'label' => 'Title',
                    'type' => 'group',
                    'divider' => true,
                    'fields' => ['title_style', 'title_decoration', 'title_font_family', 'title_color', 'title_element'],
                ],
                [
                    'label' => 'General',
                    'type' => 'group',
                    'divider' => false,
                    'fields' => $generalFields,
                ],
            ],
        ],
        '${builder.advanced}',
    ]]],
    'panels' => [
        'instantsearch-facets-order' => [
            'title' => 'Facet Order',
            'fields' => [
                'title' => [
                    'label' => 'Field',
                ],
            ],
        ],
    ],
    'transforms' => [
        'render' => function ($node) {
        },
    ],
];
